
create table public.cancha (
  id bigint generated by default as identity not null,
  complejo_id uuid null default gen_random_uuid (),
  numero bigint null,
  constraint cancha_pkey primary key (id),
  constraint cancha_complejo_id_fkey foreign KEY (complejo_id) references complejo (id) on delete CASCADE
) TABLESPACE pg_default;


create table public.cancha_reservada (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  cancha_id bigint null,
  disponible boolean null,
  constraint cancha_reservada_pkey primary key (id),
  constraint cancha_reservada_cancha_id_fkey foreign KEY (cancha_id) references cancha (id) on delete CASCADE
) TABLESPACE pg_default;


create table public.cliente (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  cancha_reservada_id bigint null,
  nombre text not null,
  constraint cliente_pkey primary key (id),
  constraint cliente_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;


create table public.complejo (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  nombre text not null,
  arrendador_id uuid null default gen_random_uuid (),
  image_url text null,
  direccion text null,
  ciudad text null,
  pais text null,
  estrellas numeric null,
  constraint complejo_pkey primary key (id),
  constraint complejo_arrendador_id_fkey foreign KEY (arrendador_id) references arrendador (id) on delete CASCADE
) TABLESPACE pg_default;


create table public.horario_disponible (
  id bigint generated always as identity not null,
  cancha_id bigint null,
  dia_semana integer null,
  hora_inicio time without time zone not null,
  hora_fin time without time zone not null,
  constraint horario_disponible_pkey primary key (id),
  constraint horario_disponible_cancha_id_fkey foreign KEY (cancha_id) references cancha (id) on delete CASCADE,
  constraint horario_disponible_dia_semana_check check (
    (
      (dia_semana >= 0)
      and (dia_semana <= 6)
    )
  )
) TABLESPACE pg_default;



create table public.reserva (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  cliente_id uuid null,
  cancha_reservada_id bigint null,
  estado text null,
  constraint reserva_pkey primary key (id),
  constraint reserva_cancha_reservada_id_fkey foreign KEY (cancha_reservada_id) references cancha_reservada (id) on delete CASCADE,
  constraint reserva_cliente_id_fkey foreign KEY (cliente_id) references cliente (id) on delete CASCADE
) TABLESPACE pg_default;




